### PR TITLE
Changed the Max Value limit of initial space from 100 mm to 200 mm

### PR DESCRIPTION
**Pull request by cmfsx**
I have change the Max Value limit of the initial space from 100 mm to 200 mm because 100 mm is not enough.

### CODE REVIEW

**Comment by mauigna06** [comment]
Hi Manjula. You can check here (https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/pull/52/files) that you changed more files than you intended.

The only file you need to change is this one (https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/blob/main/BoneReconstructionPlanner/Resources/UI/BoneReconstructionPlanner.ui)

Please correct your changes and I'll try to merge this pull request

**Comment by mauigna06** [comment]
I think it would be better if you create a new pull request without the bad commits

**Comment by lassoan** [comment]
If you just want to change a single value then you can edit the file directly on the github website. You can choose to commit directly or create a pull request.

**Comment by cmfsx** [comment]
one change was needed as the initial space cannot be increased more than 100 mm. I have changed it manually on my computer locally and thought it was the only change i done in that and someone else might come with the same problem. So i just pushed it.

**Comment by mauigna06** [comment]
Why do you needed a bigger initialSpace than 100mm? (A workaround is to start drawing the fibulaLine more proximally so the limit doesn't bother you)

In the main version of BoneReconstructionPlanner, 'initialSpace' should not be so big because this may cause that the automatic-segments-distancing may separate a little less/more of what is needed, and you would have to make bigger/smaller the 'intersection distance multiplier' to compensate or make 'intersection position' bigger (around .40 or .50) to compensate.

In the dentalImplantsBranch version I deleted 'intersection position' parameter because I remade some algorithm and it was not needed anymore. So this problem shouldn't arise.

Have in mind that autocentering the fibulaLine will only work (converge to the anatomical axis) if the fibulaLine start and end points are away from the malleolus and the head of the bone, so they are where the bone is more like a cylinder. This is something to have in mind. A centered fibulaLine is most important for fibulaSegmentRotations and not for translations.

Anyway, in spite of the previous comments, **VSP in our module is a WYSIWYG editor so the surgical plan can be visually checked** even with an uncentered fibulaLine (this was how it worked previously we had the center fibulaLine button).
As a note 'More exact planning' checkbox will try to autocenter small lines the size of the bone segment before making the transforms even if the fibulaLine has not been centered.

**Comment by cmfsx** [comment]
> A workaround is to start drawing

Yes that is how I used to work with, then i thought this would be better.



> Have in mind that autocentering the fibulaLine will only work (converge to the anatomical axis) if the fibulaLine start and end points are away from the malleolus and the head of the bone, so they are where the bone is more like a cylinder. This is something to have in mind. A centered fibulaLine is most important for fibulaSegmentRotations and not for translations.

I was not aware of that. Then I think I should not use it this way.

**Pull request closed without merging**
